# The base URL of the site; the only required configuration variable.
base_url = "https://ealib.github.io/node-mdaemon-api"

# The site title and description; used in feeds by default.
title = "Unofficial Node.js binding for MDaemon APIs"
description = ""

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "easydocs"

# When set to "true", the generated HTML files are minified.
minify_html = true

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

# Configuration of the Markdown rendering
[markdown]

# When set to "true", all code blocks are highlighted.
highlight_code = true
